### ISSUE TITLE
LOGIN WITH SMS → BUTTON を押したときにアプリがクラッシュする

### ISSUE THREAD

**Issue by fukazayo** [yamazaki8934/SelfTrainingForAndroid#2]
- エラーログ
```
2020-08-02 15:31:11.320 6527-6527/com.example.nection_android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.nection_android, PID: 6527
    java.lang.IllegalArgumentException: baseUrl must end in /: http://localhost:3000/api
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:563)
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506)
        at com.example.nection_android.api.ApiClient.getClient(ApiClient.kt:14)
        at com.example.nection_android.activities.PhoneNumberActivity.onNextButtonTapped(PhoneNumberActivity.kt:29)
        at com.example.nection_android.activities.PhoneNumberActivity$onCreate$2.onClick(PhoneNumberActivity.kt:25)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28296)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by fukazayo** [comment]
baseURLの最後に `/` を追加したら別のエラーが発生(泣)
```
2020-08-02 15:34:06.650 8209-8209/com.example.nection_android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.nection_android, PID: 8209
    java.lang.IllegalArgumentException: Form-encoded method must contain at least one @Field.
        for method PhoneAuthApis.phoneAuth
        at retrofit2.Utils.methodError(Utils.java:54)
        at retrofit2.Utils.methodError(Utils.java:43)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:216)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy2.phoneAuth(Unknown Source)
        at com.example.nection_android.activities.PhoneNumberActivity.onNextButtonTapped(PhoneNumberActivity.kt:29)
        at com.example.nection_android.activities.PhoneNumberActivity$onCreate$2.onClick(PhoneNumberActivity.kt:25)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28296)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by fukazayo** [comment]
たぶんもうちょいで直ります！

**Comment by fukazayo** [comment]
クローズします〜
